### ISSUE TITLE
Diagram z wdrożoną wysoką specjalizacją i luźnym wiązaniem

### ISSUE THREAD

**Issue by johnny333** [kolo-java-uwm-olsztyn/Prezentacje#2]
Nie jestem pewny czy diagram wysokiej specializacji i luźnego powiązania jest poprawny
P.S konstruktor car przyjmuje jeszcze dwa interfejsy,wywołuje metody interfejsu w swoich metodach
//////////////////////////////////////////////Diagram z WS i LW////////////////////////////////////////////////////////////////////// 
![zlozonyparadygmat](https://cloud.githubusercontent.com/assets/7648134/11827371/0f7c4554-a38c-11e5-8410-f4232496b1f4.jpg)

//////////////////////////////////////////////Diagram zwykły//////////////////////////////////////////////////////////////////////
![prostyparadygmat](https://cloud.githubusercontent.com/assets/7648134/11826154/c4b4632e-a383-11e5-82bb-c0640fa15871.jpg)

**Comment by cezary-butler** [comment]
To nie jest tak że są dwa podejścia do programowania obiektowego. Jest jedno, i ono wymaga zastosowania właśnie luźnego wiązania i silnej specjalizacji. Diagramy są poprawne, ale to co wydzielamy zależy głównie od realizowanego zadania.

Bez zastosowania luźnego wiązania i silnej specjalizacji używamy tylko narzędzi programowania obiektowego, nie nazwałbym tego jednak programowaniem obiektowym.
